/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-27 06:18:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ta;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bupt.ta.model.Job;
import com.bupt.ta.util.I18n;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.nio.charset.StandardCharsets;

public final class section_005fjobs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.bupt.ta.util.I18n");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
    _jspx_imports_classes.add("com.bupt.ta.model.Job");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Boolean taGuestMode = (Boolean) request.getAttribute("taGuestMode");
    if (request.getAttribute("applicant") == null && !Boolean.TRUE.equals(taGuestMode)) {
        String c = request.getContextPath();
        if (session.getAttribute("taUser") != null) {
            response.sendRedirect(c + "/ta/dashboard");
        } else {
            response.sendRedirect(c + "/ta/auth");
        }
        return;
    }
    @SuppressWarnings("unchecked")
    List<Job> openJobs = (List<Job>) request.getAttribute("openJobs");
    if (openJobs == null) openJobs = java.util.Collections.emptyList();
    Integer openJobsTotal = (Integer) request.getAttribute("openJobsTotal");
    if (openJobsTotal == null) openJobsTotal = openJobs.size();
    @SuppressWarnings("unchecked")
    Set<String> appliedJobIds = (Set<String>) request.getAttribute("appliedJobIds");
    if (appliedJobIds == null) appliedJobIds = java.util.Collections.emptySet();
    @SuppressWarnings("unchecked")
    Map<String, Integer> jobMatchScores = (Map<String, Integer>) request.getAttribute("jobMatchScores");
    if (jobMatchScores == null) jobMatchScores = java.util.Collections.emptyMap();
    String jobFilterQ = (String) request.getAttribute("jobFilterQ");
    if (jobFilterQ == null) jobFilterQ = "";
    String jobFilterType = (String) request.getAttribute("jobFilterType");
    if (jobFilterType == null) jobFilterType = "all";
    String jobFilterSort = (String) request.getAttribute("jobFilterSort");
    if (jobFilterSort == null) jobFilterSort = "newest";
    String jobFilterSkill = (String) request.getAttribute("jobFilterSkill");
    if (jobFilterSkill == null) jobFilterSkill = "";
    Boolean jobFilterHideApplied = (Boolean) request.getAttribute("jobFilterHideApplied");
    boolean hideApplied = jobFilterHideApplied != null && jobFilterHideApplied;
    @SuppressWarnings("unchecked")
    Set<String> favoriteJobIds = (Set<String>) request.getAttribute("favoriteJobIds");
    if (favoriteJobIds == null) favoriteJobIds = java.util.Collections.emptySet();
    Boolean jobFilterFavoritesOnly = (Boolean) request.getAttribute("jobFilterFavoritesOnly");
    boolean favoritesOnly = jobFilterFavoritesOnly != null && jobFilterFavoritesOnly;
    Boolean semanticMatchAvailable = (Boolean) request.getAttribute("semanticMatchAvailable");
    boolean semanticEnabled = semanticMatchAvailable != null && semanticMatchAvailable;
    String qEsc = jobFilterQ.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;");
    String skillEsc = jobFilterSkill.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;");
    @SuppressWarnings("unchecked")
    java.util.List<String> jobSkillOptions = (java.util.List<String>) request.getAttribute("jobSkillOptions");
    if (jobSkillOptions == null) jobSkillOptions = java.util.Collections.emptyList();
    String ctx = request.getContextPath();
    String guestJobsReturnPath = "/ta/dashboard";
    if (request.getQueryString() != null && !request.getQueryString().trim().isEmpty()) {
        guestJobsReturnPath += "?" + request.getQueryString();
    } else {
        guestJobsReturnPath += "?tab=jobs";
    }
    String guestJobsReturnEnc = java.net.URLEncoder.encode(guestJobsReturnPath, StandardCharsets.UTF_8);
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

      out.write("\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>");
      out.print( I18n.msg(request, "jobs.title") );
      out.write("</h2>\n");
      out.write("    <p class=\"section-desc\">");
      out.print( I18n.msg(request, "jobs.desc") );
      out.write("</p>\n");
      out.write("\n");
      out.write("    <form class=\"job-filter-bar\" method=\"get\" action=\"");
      out.print( ctx );
      out.write("/ta/dashboard\">\n");
      out.write("        <input type=\"hidden\" name=\"tab\" value=\"jobs\">\n");
      out.write("        <div>\n");
      out.write("            <label for=\"job-q\">");
      out.print( I18n.msg(request, "jobs.keyword") );
      out.write("</label>\n");
      out.write("            <input type=\"text\" id=\"job-q\" name=\"jobQ\" value=\"");
      out.print( qEsc );
      out.write("\" placeholder=\"");
      out.print( I18n.msg(request, "jobs.keyword.ph") );
      out.write("\" autocomplete=\"off\">\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("            <label for=\"job-type\">");
      out.print( I18n.msg(request, "jobs.type") );
      out.write("</label>\n");
      out.write("            <select id=\"job-type\" name=\"jobType\">\n");
      out.write("                <option value=\"all\" ");
      out.print( "all".equals(jobFilterType) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.type.all") );
      out.write("</option>\n");
      out.write("                <option value=\"course_ta\" ");
      out.print( "course_ta".equals(jobFilterType) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.type.course_ta") );
      out.write("</option>\n");
      out.write("                <option value=\"invigilation\" ");
      out.print( "invigilation".equals(jobFilterType) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.type.invigilation") );
      out.write("</option>\n");
      out.write("                <option value=\"activity\" ");
      out.print( "activity".equals(jobFilterType) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.type.activity") );
      out.write("</option>\n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("        ");

            boolean oneSkillFilter = !jobFilterSkill.isEmpty()
                    && !jobFilterSkill.contains(",") && !jobFilterSkill.contains("，")
                    && !jobFilterSkill.contains(";") && !jobFilterSkill.contains("；");
            boolean presetMatchesAny = false;
            if (oneSkillFilter) {
                String t0 = jobFilterSkill.trim();
                for (String skOpt : jobSkillOptions) {
                    if (skOpt != null && skOpt.trim().equalsIgnoreCase(t0)) {
                        presetMatchesAny = true;
                        break;
                    }
                }
            }
            boolean allSkillsPresetSelected = jobFilterSkill.isEmpty() || !oneSkillFilter || !presetMatchesAny;
        
      out.write("\n");
      out.write("        <div class=\"job-skill-wrap\">\n");
      out.write("            <span class=\"job-skill-label\">");
      out.print( I18n.msg(request, "jobs.skill") );
      out.write("</span>\n");
      out.write("            <label class=\"sr-only\" for=\"job-skill-preset\">");
      out.print( I18n.msg(request, "jobs.skill.preset") );
      out.write("</label>\n");
      out.write("            <select id=\"job-skill-preset\" class=\"job-skill-preset\" title=\"");
      out.print( I18n.msg(request, "jobs.skill.preset.title") );
      out.write("\">\n");
      out.write("                <option value=\"\" ");
      out.print( allSkillsPresetSelected ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.skill.all") );
      out.write("</option>\n");
      out.write("                ");
 for (String skOpt : jobSkillOptions) {
                    if (skOpt == null) continue;
                    String skTrim = skOpt.trim();
                    if (skTrim.isEmpty()) continue;
                    String skAttr = skTrim.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;");
                    boolean presetSel = oneSkillFilter && presetMatchesAny && skTrim.equalsIgnoreCase(jobFilterSkill.trim());
                
      out.write("\n");
      out.write("                <option value=\"");
      out.print( skAttr );
      out.write('"');
      out.write(' ');
      out.print( presetSel ? "selected" : "" );
      out.write('>');
      out.print( skAttr );
      out.write("</option>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </select>\n");
      out.write("            <label for=\"job-skill\">");
      out.print( I18n.msg(request, "jobs.skill.fuzzy") );
      out.write("</label>\n");
      out.write("            <input type=\"text\" id=\"job-skill\" name=\"jobSkill\" value=\"");
      out.print( skillEsc );
      out.write("\" placeholder=\"");
      out.print( I18n.msg(request, "jobs.skill.fuzzy.ph") );
      out.write("\" autocomplete=\"off\" list=\"job-skill-datalist\">\n");
      out.write("            <datalist id=\"job-skill-datalist\">\n");
      out.write("                ");
 for (String skOpt : jobSkillOptions) {
                    if (skOpt == null) continue;
                    String skTrim = skOpt.trim();
                    if (skTrim.isEmpty()) continue;
                    String skAttr = skTrim.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;");
                
      out.write("<option value=\"");
      out.print( skAttr );
      out.write("\"></option>");
 } 
      out.write("\n");
      out.write("            </datalist>\n");
      out.write("        </div>\n");
      out.write("        <script>\n");
      out.write("        (function () {\n");
      out.write("            var preset = document.getElementById('job-skill-preset');\n");
      out.write("            var skillInp = document.getElementById('job-skill');\n");
      out.write("            if (preset && skillInp) {\n");
      out.write("                preset.addEventListener('change', function () {\n");
      out.write("                    skillInp.value = this.value || '';\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        })();\n");
      out.write("        </script>\n");
      out.write("        <div>\n");
      out.write("            <label for=\"job-sort\">");
      out.print( I18n.msg(request, "jobs.sort") );
      out.write("</label>\n");
      out.write("            <select id=\"job-sort\" name=\"jobSort\">\n");
      out.write("                <option value=\"newest\" ");
      out.print( "newest".equals(jobFilterSort) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.sort.newest") );
      out.write("</option>\n");
      out.write("                <option value=\"oldest\" ");
      out.print( "oldest".equals(jobFilterSort) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.sort.oldest") );
      out.write("</option>\n");
      out.write("                <option value=\"match_desc\" ");
      out.print( "match_desc".equals(jobFilterSort) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.sort.matchDesc") );
      out.write("</option>\n");
      out.write("                <option value=\"title_asc\" ");
      out.print( "title_asc".equals(jobFilterSort) ? "selected" : "" );
      out.write('>');
      out.print( I18n.msg(request, "jobs.sort.titleAsc") );
      out.write("</option>\n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("        ");
 if (!Boolean.TRUE.equals(taGuestMode)) { 
      out.write("\n");
      out.write("        <div class=\"chk\">\n");
      out.write("            <input type=\"checkbox\" id=\"hide-applied\" name=\"hideApplied\" value=\"1\" ");
      out.print( hideApplied ? "checked" : "" );
      out.write(">\n");
      out.write("            <label for=\"hide-applied\">");
      out.print( I18n.msg(request, "jobs.hideApplied") );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <button type=\"submit\" class=\"btn btn-secondary btn-small\">");
      out.print( I18n.msg(request, "common.apply") );
      out.write("</button>\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/ta/dashboard?tab=jobs\" class=\"btn btn-secondary btn-small\" style=\"text-decoration:none;display:inline-block;line-height:1.25\">");
      out.print( I18n.msg(request, "jobs.reset") );
      out.write("</a>\n");
      out.write("    </form>\n");
      out.write("    <p class=\"job-filter-meta\">");
      out.print( I18n.msg(request, "jobs.meta", openJobsTotal, openJobs.size()) );
      out.write("</p>\n");
      out.write("\n");
      out.write("    ");
 @SuppressWarnings("unchecked") java.util.List<Job> recommendedJobs = (java.util.List<Job>) request.getAttribute("recommendedJobs");
       if (recommendedJobs != null && !recommendedJobs.isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"job-recommend-section\">\n");
      out.write("        <h3>");
      out.print( I18n.msg(request, "jobs.recommended.title") );
      out.write("</h3>\n");
      out.write("        <p class=\"section-desc\">");
      out.print( I18n.msg(request, "jobs.recommended.desc") );
      out.write("</p>\n");
      out.write("        <div class=\"recommended-grid\">\n");
      out.write("            ");
 for (Job rec : recommendedJobs) {
                String title = rec.getTitle() != null ? rec.getTitle() : I18n.msg(request, "jobs.unnamed");
                Integer recScore = jobMatchScores.get(rec.getId());
            
      out.write("\n");
      out.write("            <a class=\"recommended-card\" href=\"");
      out.print( ctx );
      out.write("/ta/dashboard?tab=jobs&jobQ=");
      out.print( java.net.URLEncoder.encode(title, java.nio.charset.StandardCharsets.UTF_8) );
      out.write("\">\n");
      out.write("                <strong>");
      out.print( title );
      out.write("</strong>\n");
      out.write("                <span>");
      out.print( I18n.msg(request, "jobs.match", recScore != null ? I18n.msg(request, "jobs.score.points", recScore) : I18n.msg(request, "common.dash")) );
      out.write("</span>\n");
      out.write("            </a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (favoritesOnly) { 
      out.write("\n");
      out.write("    <p class=\"section-desc job-favorites-note\">");
      out.print( I18n.msg(request, "jobs.favorites.filterActive") );
      out.write("</p>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (openJobsTotal == 0) { 
      out.write("\n");
      out.write("    <p class=\"empty-hint\">");
      out.print( I18n.msg(request, "jobs.empty.none") );
      out.write("</p>\n");
      out.write("    ");
 } else if (openJobs.isEmpty()) { 
      out.write("\n");
      out.write("    <p class=\"empty-hint\">");
      out.print( I18n.msg(request, "jobs.empty.filtered") );
      out.write("</p>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    ");
 for (Job j : openJobs) {
        if (!Job.STATUS_OPEN.equals(j.getStatus())) continue;
        boolean already = appliedJobIds.contains(j.getId());
        boolean favorited = favoriteJobIds.contains(j.getId());
        String typeLabel = "-";
        if ("course_ta".equals(j.getType())) typeLabel = I18n.msg(request, "jobs.type.course_ta");
        else if ("invigilation".equals(j.getType())) typeLabel = I18n.msg(request, "jobs.type.invigilation");
        else if ("activity".equals(j.getType())) typeLabel = I18n.msg(request, "jobs.type.activity");
        else if (j.getType() != null) typeLabel = j.getType();
        Integer mscore = jobMatchScores.get(j.getId());
        String scoreLabel = mscore != null ? I18n.msg(request, "jobs.score.points", mscore) : I18n.msg(request, "common.dash");
    
      out.write("\n");
      out.write("    <div class=\"job-card\">\n");
      out.write("        <h3>");
      out.print( j.getTitle() != null ? j.getTitle() : I18n.msg(request, "jobs.unnamed") );
      out.write("\n");
      out.write("            ");
 if (mscore != null) { 
      out.write("<span class=\"job-match-pill\" title=\"");
      out.print( I18n.msg(request, "jobs.match.title") );
      out.write('"');
      out.write('>');
      out.print( I18n.msg(request, "jobs.match", scoreLabel) );
      out.write("</span>");
 } 
      out.write("\n");
      out.write("            ");
 if (semanticEnabled && mscore != null) { 
      out.write("<span class=\"job-match-hint\">");
      out.print( I18n.msg(request, "jobs.semanticMatch") );
      out.write("</span>");
 } 
      out.write("\n");
      out.write("        </h3>\n");
      out.write("        <p class=\"section-desc job-type-label\" style=\"margin-bottom:.35rem\">\n");
      out.write("            <span class=\"badge badge-open\">");
      out.print( I18n.msg(request, "common.open") );
      out.write("</span>\n");
      out.write("            &nbsp;·&nbsp;");
      out.print( typeLabel );
      out.write("\n");
      out.write("            ");
 if (j.getCreatedAt() > 0) { 
      out.write("&nbsp;·&nbsp;");
      out.print( I18n.msg(request, "jobs.published") );
      out.write(' ');
      out.print( sdf.format(new Date(j.getCreatedAt())) );
 } 
      out.write("\n");
      out.write("        </p>\n");
      out.write("        ");
 if (j.getDescription() != null && !j.getDescription().isEmpty()) { 
      out.write("\n");
      out.write("        <p class=\"section-desc\">");
      out.print( j.getDescription() );
      out.write("</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (j.getRequiredSkills() != null && !j.getRequiredSkills().isEmpty()) { 
      out.write("\n");
      out.write("        <p class=\"section-desc\">");
      out.print( I18n.msg(request, "jobs.required") );
      out.write(' ');
      out.print( String.join("、", j.getRequiredSkills()) );
      out.write("</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <p style=\"margin:.5rem 0 0\">\n");
      out.write("            ");
 if (Boolean.TRUE.equals(taGuestMode)) {
                String dmRet = "/ta/dashboard?tab=messages&dmJobId=" + j.getId();
                String dmEsc = java.net.URLEncoder.encode(dmRet, java.nio.charset.StandardCharsets.UTF_8);
            
      out.write("\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/ta/auth?returnUrl=");
      out.print( dmEsc );
      out.write("\" class=\"btn btn-secondary btn-small\">");
      out.print( I18n.msg(request, "jobs.dmRecruiter") );
      out.write("</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/ta/dashboard?tab=messages&amp;dmJobId=");
      out.print( j.getId() );
      out.write("\" class=\"btn btn-secondary btn-small\">");
      out.print( I18n.msg(request, "jobs.dmRecruiter") );
      out.write("</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </p>\n");
      out.write("        ");
 if (!Boolean.TRUE.equals(taGuestMode)) { 
      out.write("\n");
      out.write("        <form method=\"post\" action=\"");
      out.print( ctx );
      out.write("/ta/dashboard\" class=\"favorite-form\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"toggleFavorite\">\n");
      out.write("            <input type=\"hidden\" name=\"jobId\" value=\"");
      out.print( j.getId() );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"favorited\" value=\"");
      out.print( favorited ? "0" : "1" );
      out.write("\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-outline btn-small\">");
      out.print( favorited ? I18n.msg(request, "jobs.unfavorite") : I18n.msg(request, "jobs.favorite") );
      out.write("</button>\n");
      out.write("        </form>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (already) { 
      out.write("\n");
      out.write("        <p class=\"applied-tag\">");
      out.print( I18n.msg(request, "jobs.appliedTag") );
      out.write("</p>\n");
      out.write("        ");
 } else if (Boolean.TRUE.equals(taGuestMode)) { 
      out.write("\n");
      out.write("        <p style=\"margin:.5rem 0 0\">\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/ta/auth?returnUrl=");
      out.print( guestJobsReturnEnc );
      out.write("\" class=\"btn btn-primary\">");
      out.print( I18n.msg(request, "dash.ta.guest.applyLogin") );
      out.write("</a>\n");
      out.write("        </p>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <form method=\"post\" action=\"");
      out.print( ctx );
      out.write("/ta/dashboard\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"apply\">\n");
      out.write("            <input type=\"hidden\" name=\"jobId\" value=\"");
      out.print( j.getId() );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"jobQ\" value=\"");
      out.print( qEsc );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"jobType\" value=\"");
      out.print( jobFilterType );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"jobSort\" value=\"");
      out.print( jobFilterSort );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"jobSkill\" value=\"");
      out.print( skillEsc );
      out.write("\">\n");
      out.write("            ");
 if (hideApplied) { 
      out.write("<input type=\"hidden\" name=\"hideApplied\" value=\"1\">");
 } 
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>");
      out.print( I18n.msg(request, "jobs.note") );
      out.write("</label>\n");
      out.write("                <input type=\"text\" name=\"note\" placeholder=\"");
      out.print( I18n.msg(request, "jobs.note.ph") );
      out.write("\">\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">");
      out.print( I18n.msg(request, "jobs.apply.btn") );
      out.write("</button>\n");
      out.write("        </form>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("<style>\n");
      out.write(".job-recommend-section { margin: 1.5rem 0 0; padding: 1rem 1rem 0; border-top: 1px solid #e5e7eb; }\n");
      out.write(".recommended-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 0.75rem; margin-top: 0.75rem; }\n");
      out.write(".recommended-card { display: block; padding: 1rem; border: 1px solid #e2e8f0; border-radius: 0.9rem; text-decoration: none; color: inherit; background: #ffffff; transition: transform .15s ease, border-color .15s ease; }\n");
      out.write(".recommended-card:hover { transform: translateY(-2px); border-color: #60a5fa; }\n");
      out.write(".recommended-card strong { display: block; margin-bottom: 0.45rem; font-size: 0.95rem; }\n");
      out.write(".recommended-card span { color: #475569; font-size: 0.85rem; }\n");
      out.write(".job-favorites-note { margin-top: 0.5rem; font-size: 0.95rem; color: #065f46; }\n");
      out.write(".job-match-hint { margin-left: 0.6rem; font-size: 0.8rem; color: #2563eb; padding: 0.08rem 0.45rem; background: rgba(37,99,235,.08); border-radius: 0.65rem; vertical-align: middle; }\n");
      out.write(".favorite-form { margin-top: 0.5rem; }\n");
      out.write(".favorite-form .btn { padding: 0.5rem 0.9rem; }\n");
      out.write("</style>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
