/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-27 06:17:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bupt.ta.util.I18n;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.bupt.ta.util.I18n");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"");
      out.print( I18n.htmlLangAttr(request) );
      out.write("\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>");
      out.print( I18n.msg(request, "home.pageTitle") );
      out.write("</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css?v=4\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/assistant.css?v=9\">\n");
      out.write("    <style>\n");
      out.write("      * { box-sizing: border-box; }\n");
      out.write("      body.home { margin: 0; font-family: \"PingFang SC\",\"Microsoft YaHei\",sans-serif; min-height: 100vh;\n");
      out.write("        background: linear-gradient(165deg, #eef6ff 0%, #e0f2fe 38%, #f1f5f9 72%, #f8fafc 100%); color: #1e293b; }\n");
      out.write("      .home-top-pc {\n");
      out.write("        position: fixed; top: 0.85rem; right: 1rem; left: 1rem; z-index: 20;\n");
      out.write("        display: flex; align-items: center; justify-content: flex-end; flex-wrap: wrap; gap: 0.5rem 0.65rem;\n");
      out.write("        max-width: 960px; margin-left: auto; margin-right: auto;\n");
      out.write("      }\n");
      out.write("      .home-top-pc .home-quick-nav {\n");
      out.write("        display: inline-flex; align-items: center; gap: 0.35rem; flex-wrap: wrap;\n");
      out.write("        padding: 0.35rem 0.65rem; background: rgba(255,255,255,0.88); border: 1px solid #e2e8f0; border-radius: 999px;\n");
      out.write("        box-shadow: 0 2px 10px rgba(0,0,0,0.05); font-size: 0.82rem;\n");
      out.write("      }\n");
      out.write("      .home-top-pc .home-quick-nav a { color: #475569; text-decoration: none; padding: 0.2rem 0.45rem; border-radius: 6px; }\n");
      out.write("      .home-top-pc .home-quick-nav a:hover { color: #2563eb; background: #eff6ff; }\n");
      out.write("      .home-top-pc .home-quick-nav span { color: #cbd5e1; user-select: none; }\n");
      out.write("      .home-top-pc > a.personal-center-btn {\n");
      out.write("        display: inline-flex; align-items: center; gap: 0.45rem; padding: 0.45rem 0.9rem 0.45rem 0.65rem;\n");
      out.write("        background: rgba(255,255,255,0.92); border: 1px solid #e2e8f0; border-radius: 999px;\n");
      out.write("        text-decoration: none; color: #1e293b; font-size: 0.9rem; font-weight: 500;\n");
      out.write("        box-shadow: 0 2px 10px rgba(0,0,0,0.06); transition: box-shadow 0.2s ease, border-color 0.2s ease;\n");
      out.write("      }\n");
      out.write("      .home-top-pc > a.personal-center-btn:hover { border-color: #93c5fd; box-shadow: 0 4px 16px rgba(37,99,235,0.12); }\n");
      out.write("      .home-top-pc .pc-icon { width: 28px; height: 28px; border-radius: 50%; background: #dbeafe; color: #2563eb;\n");
      out.write("        display: flex; align-items: center; justify-content: center; font-size: 0.95rem; flex-shrink: 0; }\n");
      out.write("      .container { max-width: 920px; margin: 0 auto; padding: 4.25rem 1.5rem 2.5rem; }\n");
      out.write("      header {\n");
      out.write("        text-align: center; margin-bottom: 2.35rem;\n");
      out.write("        padding: 2rem 1.5rem 2.25rem;\n");
      out.write("        background: rgba(255,255,255,0.72);\n");
      out.write("        border: 1px solid rgba(226,232,240,0.9);\n");
      out.write("        border-radius: 20px;\n");
      out.write("        box-shadow: 0 4px 32px rgba(15,23,42,0.06), 0 1px 0 rgba(255,255,255,0.9) inset;\n");
      out.write("        backdrop-filter: blur(12px);\n");
      out.write("        -webkit-backdrop-filter: blur(12px);\n");
      out.write("        position: relative;\n");
      out.write("        overflow: hidden;\n");
      out.write("      }\n");
      out.write("      header::before {\n");
      out.write("        content: \"\"; position: absolute; left: 0; right: 0; top: 0; height: 4px;\n");
      out.write("        background: linear-gradient(90deg, #3b82f6, #6366f1, #8b5cf6);\n");
      out.write("        opacity: 0.92;\n");
      out.write("      }\n");
      out.write("      header h1 { font-size: clamp(1.5rem, 4vw, 1.95rem); font-weight: 700; color: #0f172a; margin: 0; letter-spacing: -0.03em; }\n");
      out.write("      .subtitle { color: #64748b; font-size: 0.95rem; margin-top: 0.65rem; line-height: 1.55; }\n");
      out.write("      .home-section { margin-bottom: 2.25rem; }\n");
      out.write("      .home-section:last-of-type { margin-bottom: 0; }\n");
      out.write("      .home-section-title {\n");
      out.write("        font-size: 0.72rem; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase;\n");
      out.write("        color: #94a3b8; margin: 0 0 0.35rem;\n");
      out.write("      }\n");
      out.write("      .home-section-desc { font-size: 0.88rem; color: #64748b; margin: 0 0 1rem; line-height: 1.5; }\n");
      out.write("      .cards { display: grid; gap: 1.25rem; }\n");
      out.write("      .cards--identity { grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); }\n");
      out.write("      .cards--tools { grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); }\n");
      out.write("      .card {\n");
      out.write("        display: block; background: #fff; border-radius: 14px; padding: 1.75rem 1.65rem; text-decoration: none; color: inherit;\n");
      out.write("        box-shadow: 0 2px 8px rgba(15,23,42,0.06), 0 8px 24px rgba(15,23,42,0.04); border: 1px solid rgba(226,232,240,0.95);\n");
      out.write("        transition: transform 0.22s ease, box-shadow 0.22s ease, border-color 0.2s ease;\n");
      out.write("      }\n");
      out.write("      .card:hover { transform: translateY(-4px); box-shadow: 0 12px 40px rgba(37,99,235,0.12); border-color: #bfdbfe; }\n");
      out.write("      .card--emphasis { border-color: #bfdbfe; box-shadow: 0 6px 20px rgba(37,99,235,0.08); }\n");
      out.write("      .card--soft { padding: 1.35rem 1.5rem; background: #fafbfc; }\n");
      out.write("      .card-icon { width: 48px; height: 48px; display: flex; align-items: center; justify-content: center; font-size: 1.5rem;\n");
      out.write("        background: #dbeafe; color: #2563eb; border-radius: 6px; margin-bottom: 1rem; }\n");
      out.write("      .card--soft .card-icon { width: 40px; height: 40px; font-size: 1.25rem; background: #eef2ff; color: #4f46e5; }\n");
      out.write("      .card h2 { font-size: 1.15rem; font-weight: 600; margin: 0 0 0.4rem; color: #1e293b; }\n");
      out.write("      .card p { font-size: 0.9rem; color: #64748b; margin: 0; line-height: 1.5; }\n");
      out.write("      .home-admin-row {\n");
      out.write("        display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 0.75rem 1rem;\n");
      out.write("        padding: 1rem 1.25rem; background: rgba(255,255,255,0.75); border: 1px solid #e2e8f0; border-radius: 10px;\n");
      out.write("        text-decoration: none; color: #475569; font-size: 0.9rem; transition: border-color 0.2s, box-shadow 0.2s;\n");
      out.write("      }\n");
      out.write("      .home-admin-row:hover { border-color: #c7d2fe; box-shadow: 0 4px 16px rgba(79,70,229,0.08); color: #1e293b; }\n");
      out.write("      .home-admin-row strong { color: #334155; font-weight: 600; }\n");
      out.write("      .home-admin-row span.meta { font-size: 0.82rem; color: #94a3b8; }\n");
      out.write("      footer { text-align: center; margin-top: 2rem; font-size: 0.8rem; color: #64748b; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"home\">\n");
      out.write("    ");

        String ctx = request.getContextPath();
        String personalCenterHref = ctx + "/personal-center";
        if (session.getAttribute("taUser") != null) {
            personalCenterHref = ctx + "/ta/profile";
        } else if (session.getAttribute("moUser") != null) {
            personalCenterHref = ctx + "/mo/profile";
        } else if (session.getAttribute("adminUser") != null) {
            personalCenterHref = ctx + "/admin/workload";
        }
    
      out.write("\n");
      out.write("    <div class=\"home-top-pc\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/lang_switch.jsp", out, false);
      out.write("\n");
      out.write("        <nav class=\"home-quick-nav\" aria-label=\"");
      out.print( I18n.msg(request, "home.quickNavAria") );
      out.write("\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/forum\">");
      out.print( I18n.msg(request, "common.forum") );
      out.write("</a>\n");
      out.write("            <span aria-hidden=\"true\">·</span>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assistant\">");
      out.print( I18n.msg(request, "common.assistant") );
      out.write("</a>\n");
      out.write("        </nav>\n");
      out.write("        <a href=\"");
      out.print( personalCenterHref );
      out.write("\" class=\"personal-center-btn\"><span class=\"pc-icon\" aria-hidden=\"true\">👤</span>");
      out.print( I18n.msg(request, "common.personalCenter") );
      out.write("</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <header>\n");
      out.write("            <h1>");
      out.print( I18n.msg(request, "home.title") );
      out.write("</h1>\n");
      out.write("            <p class=\"subtitle\">");
      out.print( I18n.msg(request, "home.subtitle") );
      out.write("</p>\n");
      out.write("        </header>\n");
      out.write("        <main>\n");
      out.write("            <section class=\"home-section\" aria-labelledby=\"home-identity\">\n");
      out.write("                <h2 id=\"home-identity\" class=\"home-section-title\">");
      out.print( I18n.msg(request, "home.section.identity") );
      out.write("</h2>\n");
      out.write("                <p class=\"home-section-desc\">");
      out.print( I18n.msg(request, "home.section.identity.desc") );
      out.write("</p>\n");
      out.write("                <div class=\"cards cards--identity\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ta/dashboard\" class=\"card card--emphasis\">\n");
      out.write("                        <div class=\"card-icon\">👤</div>\n");
      out.write("                        <h2>");
      out.print( I18n.msg(request, "home.card.ta") );
      out.write("</h2>\n");
      out.write("                        <p>");
      out.print( I18n.msg(request, "home.card.ta.desc") );
      out.write("</p>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mo/dashboard\" class=\"card card--emphasis\">\n");
      out.write("                        <div class=\"card-icon\">📋</div>\n");
      out.write("                        <h2>");
      out.print( I18n.msg(request, "home.card.mo") );
      out.write("</h2>\n");
      out.write("                        <p>");
      out.print( I18n.msg(request, "home.card.mo.desc") );
      out.write("</p>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <section class=\"home-section\" aria-labelledby=\"home-tools\">\n");
      out.write("                <h2 id=\"home-tools\" class=\"home-section-title\">");
      out.print( I18n.msg(request, "home.section.tools") );
      out.write("</h2>\n");
      out.write("                <p class=\"home-section-desc\">");
      out.print( I18n.msg(request, "home.section.tools.desc") );
      out.write("</p>\n");
      out.write("                <div class=\"cards cards--tools\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/forum\" class=\"card card--soft\">\n");
      out.write("                        <div class=\"card-icon\">💬</div>\n");
      out.write("                        <h2>");
      out.print( I18n.msg(request, "home.card.forum") );
      out.write("</h2>\n");
      out.write("                        <p>");
      out.print( I18n.msg(request, "home.card.forum.desc") );
      out.write("</p>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assistant\" class=\"card card--soft\">\n");
      out.write("                        <div class=\"card-icon\">🤖</div>\n");
      out.write("                        <h2>");
      out.print( I18n.msg(request, "home.card.assistant") );
      out.write("</h2>\n");
      out.write("                        <p>");
      out.print( I18n.msg(request, "home.card.assistant.desc") );
      out.write("</p>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <section class=\"home-section\" aria-labelledby=\"home-admin\">\n");
      out.write("                <h2 id=\"home-admin\" class=\"home-section-title\">");
      out.print( I18n.msg(request, "home.section.admin") );
      out.write("</h2>\n");
      out.write("                <p class=\"home-section-desc\">");
      out.print( I18n.msg(request, "home.section.admin.desc") );
      out.write("</p>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/auth\" class=\"home-admin-row\">\n");
      out.write("                    <span>");
      out.print( I18n.msg(request, "home.admin.row") );
      out.write("</span>\n");
      out.write("                    <span class=\"meta\">");
      out.print( I18n.msg(request, "home.admin.meta") );
      out.write("</span>\n");
      out.write("                </a>\n");
      out.write("            </section>\n");
      out.write("        </main>\n");
      out.write("        <footer>\n");
      out.write("            <p>");
      out.print( I18n.msg(request, "home.footer") );
      out.write("</p>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assistant\" class=\"assistant-fab\" title=\"");
      out.print( I18n.msg(request, "home.fab.title") );
      out.write("\"><span class=\"assistant-fab-icon\" aria-hidden=\"true\">🤖</span>");
      out.print( I18n.msg(request, "home.fab.label") );
      out.write("</a>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
